# Generated by Django 5.2.3 on 2025-07-23 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique identifier for the device/browser', max_length=100)),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.event')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'reaction'], name='core_eventl_event_i_f57cc4_idx'), models.Index(fields=['device_id'], name='core_eventl_device__0792e6_idx')],
                'unique_together': {('event', 'device_id')},
            },
        ),
    ]
