# Generated by Django 5.2.3 on 2025-08-21 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_galleryimage_alter_verselike_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousVerseInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('interaction_type', models.CharField(choices=[('like', 'Like'), ('share', 'Share')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerseShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('share_method', models.CharField(choices=[('native', 'Native Share'), ('clipboard', 'Clipboard'), ('social', 'Social Media')], default='clipboard', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='bibleverse',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='verselike',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='bibleverse',
            old_name='verse_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='bibleverse',
            name='date',
        ),
        migrations.AddField(
            model_name='bibleverse',
            name='book',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bibleverse',
            name='chapter',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bibleverse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bibleverse',
            name='daily_date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bibleverse',
            name='is_daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bibleverse',
            name='verse_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bibleverse',
            name='verse_start',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verselike',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verselike',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verselike',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.bibleverse'),
        ),
        migrations.AlterUniqueTogether(
            name='verselike',
            unique_together={('user', 'verse')},
        ),
        migrations.AddIndex(
            model_name='bibleverse',
            index=models.Index(fields=['daily_date'], name='core_biblev_daily_d_6779b8_idx'),
        ),
        migrations.AddIndex(
            model_name='bibleverse',
            index=models.Index(fields=['is_daily'], name='core_biblev_is_dail_b555f1_idx'),
        ),
        migrations.AddField(
            model_name='anonymousverseinteraction',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_interactions', to='core.bibleverse'),
        ),
        migrations.AddField(
            model_name='verseshare',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verseshare',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='core.bibleverse'),
        ),
        migrations.AddIndex(
            model_name='anonymousverseinteraction',
            index=models.Index(fields=['verse', 'interaction_type'], name='core_anonym_verse_i_131b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymousverseinteraction',
            index=models.Index(fields=['ip_address', 'session_key'], name='core_anonym_ip_addr_5562db_idx'),
        ),
    ]
